# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20170127_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='aobcg',
        ),
        migrations.RemoveField(
            model_name='order',
            name='aohepb',
        ),
        migrations.RemoveField(
            model_name='order',
            name='aohpv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='aomeasles',
        ),
        migrations.RemoveField(
            model_name='order',
            name='aoopv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='aopcv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='aott',
        ),
        migrations.RemoveField(
            model_name='order',
            name='aoyf',
        ),
        migrations.RemoveField(
            model_name='order',
            name='commbcg',
        ),
        migrations.RemoveField(
            model_name='order',
            name='commhepb',
        ),
        migrations.RemoveField(
            model_name='order',
            name='commhpv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='commmeasles',
        ),
        migrations.RemoveField(
            model_name='order',
            name='commopv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='commpcv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='commtt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='commyf',
        ),
        migrations.RemoveField(
            model_name='order',
            name='oqbcg',
        ),
        migrations.RemoveField(
            model_name='order',
            name='oqhepb',
        ),
        migrations.RemoveField(
            model_name='order',
            name='oqhpv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='oqmeasles',
        ),
        migrations.RemoveField(
            model_name='order',
            name='oqopv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='oqpcv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='oqtt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='oqyf',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sbbcg',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sbhepb',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sbhpv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sbmeasles',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sbopv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sbpcv',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sbtt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sbyf',
        ),
    ]
